//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYLQ.SqlServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LYLQEntities : DbContext
    {
        public LYLQEntities()
            : base("name=LYLQEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Department> Departments { get; set; }
        public DbSet<InStore> InStores { get; set; }
        public DbSet<Materiel> Materiels { get; set; }
        public DbSet<OutStore> OutStores { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
