//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYLQ.SqLite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LYLQEntities : DbContext
    {
        public LYLQEntities()
            : base("name=LYLQEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InStore> InStores { get; set; }
        public virtual DbSet<OutStore> OutStores { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Materiel> Materiels { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
